### ISSUE TITLE
Accept binary matrix input or create helper function for conversion

### ISSUE THREAD

**Issue by moldach** [upsetjs/upsetjs_r#10]
A number of tools, like SURVIVOR, create binary matrix. Tools like ComplexHeatmap's UpSet plot can either accept input from A) lists of sets (like `upsetjs_r`) or B) binary matrix.

It would be nice if `upsetjs_r` could either accept input from binary matrices or contain a helper function to convert binary matrix data.

I don't believe ComplexHeatmap (or any other package I know of) has a function to do this at the moment: https://support.bioconductor.org/p/131616/

**Comment by sgratzl** [comment]
can you provide a sample dataset, please?

**Comment by moldach** [comment]
Sure:

```
library(tibble)
mat <- tribble(
  ~set1, ~set2, ~set3,
   1,   1,   0,
   0,   0,   1,
   0,   1,   1,
   0,   0,   1,
   0,   0,   1,
   0,   1,   1,
   1,   0,   1,
   0,   1,   1,
   0,   0,   1,
   0,   0,   1,
   1,   1,   1,
   1,   0,   0,
   0,   0,   1,
   0,   1,   0,
   1,   1,   1,
   0,   1,   0,
   0,   1,   1,
   0,   1,   0,
   0,   0,   1,
   0,   0,   1
)
```

So either accept that type of data or a helper function to convert it into a format that `upsetjs` accepts, _e.g._:

```
set.seed(123)
listInput = list(a = sample(letters, 5),
          b = sample(letters, 10),
          c = sample(letters, 15))
upsetjs() %>% fromList(listInput) %>% interactiveChart()
```

**Comment by sgratzl** [comment]
https://upset.js.org/integrations/r/articles/basic.html#data-frame-input doesn't work?

**Comment by moldach** [comment]
Sorry I never saw that documentation - I still [cannot find a link for it on the README on the github repo](https://github.com/upsetjs/upsetjs_r/).

One more thing, I've noticed the following discrepancy.

```
library(tibble)
t <- tribble(
  ~set1, ~set2, ~set3,
   1,   1,   0,
   0,   0,   1,
   0,   1,   1,
   0,   0,   1,
   0,   0,   1,
   0,   1,   1,
   1,   0,   1,
   0,   1,   1,
   0,   0,   1,
   0,   0,   1,
   1,   1,   1,
   1,   0,   0,
   0,   0,   1,
   0,   1,   0,
   1,   1,   1,
   0,   1,   0,
   0,   1,   1,
   0,   1,   0,
   0,   0,   1,
   0,   0,   1
)
```

Both `VennDiagram` and `ComplexHeatmap` produce the same result but `upsetjs` was producing a different image.

# VennDiagram

```
library(VennDiagram)
venn.diagram(list(Set1=which(t[,1]==1), 
                  Set2=which(t[,2]==1), 
                  Set3=which(t[,3]==1)), 
             fill = c("#DDAA33", "#BB5566" ,"#004488"), 
             alpha = c(0.5, 0.5, 0.5), cex = 2, lty =2, 
             filename = "VennDiagram.tiff")
```

![venn](https://user-images.githubusercontent.com/5749465/84092253-0cab9400-a9b4-11ea-87b0-cfacaf0c5e40.PNG)


# ComplexHeatmap

```
m = make_comb_mat(t)
ss = set_size(m)
UpSet(m, set_order = order(ss), comb_order = order(-comb_size(m)))
```

![Rplot01](https://user-images.githubusercontent.com/5749465/84092579-04078d80-a9b5-11ea-9202-17799820715b.png)


# UpSetJS

```
upsetjs() %>% fromDataFrame(t)
```

![Rplot03](https://user-images.githubusercontent.com/5749465/84092284-22b95480-a9b4-11ea-963e-cc3ee5c64134.png)


According to ComplexHeatmap's documentation:

> `intersect` mode: 1 means in that set and 0 is not taken into account, then, 1 1 0 means a set of elements in set A and B, and they can also in C or not in C (intersect(A, B)). Under this mode, the seven combination sets can overlap.

so,

```
m = make_comb_mat(t, mode="intersect")
ss = set_size(m)
UpSet(m, 
           set_order = order(ss),
           #comb_order = order(comb_degree(m), -cs),
           comb_order = order(-comb_size(m)))
```

![Rplot03](https://user-images.githubusercontent.com/5749465/84092500-cc98e100-a9b4-11ea-8a47-f903a53c9fe1.png)


So for ComplexHeatmap the default is `distinct`

> `distinct` mode: 1 means in that set and 0 means not in that set, then 1 1 0 means a set of elements both in set A and B, while not in C (setdiff(intersect(A, B), C)). Under this mode, the seven combination sets are the seven partitions in the Venn diagram and they are mutually exclusive.

How can you mimic the `distinct` output produced by **VennDiagram** and **ComplexHeatmap** with `UpSetJS`?

**Comment by sgratzl** [comment]
so to understand it correctly

> m = make_comb_mat(t)
> ss = set_size(m)
> UpSet(m, set_order = order(ss), comb_order = order(-comb_size(m)))

if you label the vertical bars in this chart it would read the following: 

- setdiff(set3, union(set1, set2))
- setdiff(intersect(set3,set3), set1)
- setdiff(set2, union(set1, set3))
- intersect(set3, set2, set3)
- setdiff(intersect(set2, set1), set3)
- setdiff(intersect(set3, set1), set2)
- setdiff(set1, union(set3,set2))

right?

**Comment by jokergoo** [comment]
E.g., in **ComplexHeatmap**, for a pattern

```
A B C
x x -
```
the "distinct" mode corresponds to `setdiff(intersect(A, B), C)` and the "intersect" mode corresponds to `intersect(A, B)`, 

and similar for the pattern:

```
A B C
x - -
```

the "distinct" mode corresponds to `setdiff(setdiff(A, B), C)`, or `setdiff(A, union(B, C))`, the "intersect" mode corresponds to `intersect(A)` which is `A`.

You can find the graphical explanations here:

![image](https://user-images.githubusercontent.com/449218/84166514-48f2f900-aa75-11ea-8c2a-ab0a560dbdba.png)

**Comment by moldach** [comment]
Thank you for clarification @jokergoo

**Comment by sgratzl** [comment]
thx. I just implemented a `generateDistinctIntersections()` function. 

can you verify that https://upset.js.org/next/integrations/r/articles/combinationModes.html is now showing the values you would expect in the different modes?

**Comment by moldach** [comment]
That's awesome @sgratzl , thanks for being so quick with this enhancement! 

The function may not have been included in the most recent build though.

I deleted the folder from R/win-library/4.0 and tried to reinstall via: `devtools::install_url("https://github.com/upsetjs/upsetjs_r/releases/latest/download/upsetjs.tar.gz")`

but I get an error:

```
t <- read.csv("data/survivor_comparison_matrix.csv")
library(upsetjs)
upsetjs() %>% 
  fromDataFrame(t) %>% 
  generateDistinctIntersections() %>%   
  interactiveChart()
```

> Error in generateDistinctIntersections(.) : 
  could not find function "generateDistinctIntersections"

**Comment by sgratzl** [comment]
yeah it is not released yet but in the develop branch. You can download a current build e.g. from https://github.com/upsetjs/upsetjs.github.io/raw/master/next/integrations/r/upsetjs.tar.gz

**Comment by sgratzl** [comment]
version 1.1.0 has been released containing the `generateDistinctIntersections` function
