### ISSUE TITLE
The vertical bars for the unique elements of a set show the total elements of the set instead

### ISSUE THREAD

**Issue by lianos** [upsetjs/upsetjs_r#13]
The sections (vertical bars) of an upset plot that (I believe) are meant to show the number of unique elements in the set rather show the number of total elements in the set instead (ie. what is shown in the horizontal bars for the set).

**To Reproduce**

This data and code:

```r
exdata <- list(
  a = head(letters, 20),
  b = letters[8:10],
  c = letters[10:20],
  d = tail(letters, -10))

upsetjs::upsetjs() %>% 
  upsetjs::fromList(exdata)
```

Shows this plot. Bars outlined in blue, red, and orange are the ones  are the problematic ones:

<img width="805" alt="upsetjsplot" src="https://user-images.githubusercontent.com/25496/88116956-b57e0f00-cb6e-11ea-9b6f-c315968ec1ba.png">

**Expected behavior**

I expected a plot similar to the one produced by UpSetR using this code:

```r
UpSetR::fromList(exdata) %>% UpSetR::upset()
```

Only the blue and red boxed bars are highlighted because they are the only sets that have unique elements to them.

<img width="917" alt="UpSetRplot" src="https://user-images.githubusercontent.com/25496/88117215-61bff580-cb6f-11ea-87af-473ff7993279.png">

- Version: upsetjs R package v1.6.0
- Browser: Not sure its relevant because its the same for static and interactive plots, but this is from within RStudio IDE v1.3.959

**More Context**

Actually, after further inspection of the two plots, it seems upsetjs seems to be double counting in other places too. For instance, the number of elements in the **b** and **a** intersection should only be two instead of 3, because the third element being counted there belongs to the intersection of sets **b**, **c**, and **a**, namely the 10th letter of the alphabet (`"j"`).

This looks like a very promising package so far, though. Thanks for all of your hard work!

**Comment by lianos** [comment]
For what it's worth, the same data as presented via `upsetjs::upsetjsVennDiagram()` shows the correct tabulation, ie.

```r
exdata <- list(
  a = head(letters, 20),
  b = letters[8:10],
  c = letters[10:20],
  d = tail(letters, -10))

upsetjs::upsetjsVennDiagram() %>%
  upsetjs::fromList(exdata) %>%
  upsetjs::interactiveChart()
```

Shows, for example, ony 7 unique elements to set **a**

<img src="https://user-images.githubusercontent.com/25496/88118371-42769780-cb72-11ea-8d24-9cdfbe247e9a.png" width = "50%">

**Comment by sgratzl** [comment]
I guess you are looking for the `distinct intersection mode`:

https://upset.js.org/integrations/r/articles/combinationModes.html#distinct-intersection-mode

**Comment by lianos** [comment]
Ahhhh, well ... that's embarrassing. Yes, that would indeed be what I'm looking for, thanks :-)
