### ISSUE TITLE
Get the information of selected part

### ISSUE THREAD

**Issue by larry1995** [upsetjs/upsetjs_r#15]
It would be great if you can tell me how to render the data table of selected parts on the UpSet plot and Venn Plot as you show on your website. 

**User story**

I am using R shiny to implement the upsetjs package. I can't find any sample code for this feature. 

**Additional context**

**Comment by sgratzl** [comment]
have yo looked at https://github.com/upsetjs/upsetjs_r/blob/main/r_package/shiny/events.R?

this is an example how UpSet.js talks back to the shiny server

**Comment by larry1995** [comment]
Hi @sgratzl ,

Thank you for your answer. Yes, I used clicked$names to fetch the names but I don't know how to get the intersection parts back. Will it come back from the upset.js instance or somewhere?

**Comment by sgratzl** [comment]
The example consists of two parts:

https://github.com/upsetjs/upsetjs_r/blob/872c5df088244abd97b9bcee6ca0c3b48ce52aca/r_package/shiny/events.R#L41-L47

the first one is about the selected intersection name, the other about the selected elements. I don't understand what else you are looking for
