### ISSUE TITLE
Is it possible to change the hoverBar text colour and rectangle on an interactive chart?

### ISSUE THREAD

**Issue by sa-lee** [upsetjs/upsetjs_r#20]
Hello!
Thanks for this package, it's been super useful and easy to use. 

Apologies if I missed this in the docs, but it was unclear to me how to modify the on hover text and rectangle element on an interactive upset chart - as shown in the linked screenshot. I want to change the colour to a darker one, and increase the font size of the label. Is this possible? 
![Screen Shot 2021-10-28 at 8 20 22 pm](https://user-images.githubusercontent.com/8033857/139227138-389d39ec-ef00-4300-89c1-942c213406a9.png)

Thanks,
Stuart

**Comment by sgratzl** [comment]
you can try:

```R
listInput <- list(one = c('a', 'b', 'c', 'e', 'g', 'h', 'k', 'l', 'm'), two = c('a', 'b', 'd', 'e', 'j'), three = c('a', 'e', 'f', 'g', 'h', 'i', 'j', 'l', 'm'))
w <- upsetjs() %>% fromList(listInput) %>% interactiveChart() %>% chartFontSizes(bar.label='20px') %>% chartTheme(hover.hint.color = 'red')
```

**Comment by sa-lee** [comment]
Thanks! Sorry I forgot to reply to this
