### ISSUE TITLE
generateIntersections improvement

### ISSUE THREAD

**Issue by vagkaratzas** [upsetjs/upsetjs_r#23]
The generateIntersections function generally works fine.

However, for the single-group bars, I think their unique elements should be shown instead of their total data.

These specific bars are currently redundant with the horizontal bars (Set Size).

**Comment by sgratzl** [comment]
have you seen https://upset.js.org/integrations/r/articles/combinationModes.html?

**Comment by vagkaratzas** [comment]
Yes, in the Intersection Mode example of this link, set 3 has 15 elements.

Since it shares 6 items with set 2 and 3 items with set 1, its vertical bar (the first one) should have a count of 15-9 = 6 (unique items, instead of 15 total, which is already shown in its horizontal bar)

**Comment by vagkaratzas** [comment]
Ooh, hadn't noticed the generateDistinctIntersections function.

This does exactly that. Thank you
