### ISSUE TITLE
order set names

### ISSUE THREAD

**Issue by dwill023** [upsetjs/upsetjs_r#30]
Hi, I would like to know if there is a way to manually order the sets. For example in the below pic. my upset plot is ordered by cardinality (from highest to lowest, bottom to top). Can I make it where the sets in purple are on the bottom then the teal sets, yellow then red at top? 

![Capture](https://user-images.githubusercontent.com/38054440/187311590-20cc9ffb-cbab-48c4-b03c-076e9d56e9ba.JPG)

I've tried setting order.by = "degree" in fromList() but that just orders the sets alphabetically. 

- Version:
   - R version 4.2.1 
   - upsetjs_1.11.1  
- Browser: Chrome

Thanks!

**Comment by sgratzl** [comment]
by default you can order the sets by cardinality (default) or by name (`order.by` argument of e.g. `fromList`). However, you can also retrieve the sets using `getSets` order by whatever you want and set them again using `setSets`

**Comment by ghost** [comment]
Yeah the order.by argument of fromList has only the options order.by == "cardinality" || order.by == "degree" not by name. So this didn't work for me.
