### ISSUE TITLE
Ellipses in Euler diagrams

### ISSUE THREAD

**Issue by karlmakepeace** [upsetjs/upsetjs_r#33]
It would be great if the Euler diagram functions supported ellipses (e.g.: [`eulerr` package](https://cran.r-project.org/web/packages/eulerr/index.html)) as they allow for less error in the the set area representation ([link](https://cran.r-project.org/web/packages/eulerr/vignettes/introduction.html) includes explanation & example(s)).

e.g. Euler plot constructed with ellipses (pasted from [link](https://cran.r-project.org/web/packages/eulerr/vignettes/introduction.html)):

![image](https://user-images.githubusercontent.com/6200041/204684353-aaeaabdb-673a-4e40-9549-e11d1506e721.png)

**Comment by sgratzl** [comment]
this package is using https://github.com/benfred/venn.js/ as the underlying library for computing Euler diagrams. You could post it in this or in my maintained fork at https://github.com/upsetjs/venn.js

**Comment by karlmakepeace** [comment]
I have now re-posted the request in "[upsetjs/venn.js](https://github.com/upsetjs/venn.js/issues/42#issue-1470762514)".

Thank you. 👍🏽
